### ISSUE TITLE
collaboration on vault operators?

### ISSUE THREAD

**Issue by raffaelespazzoli** [patoarvizu/vault-dynamic-configuration-operator#48]
hello, sorry but I didn't know how else to contact you. I'm writing an operator with a similar aim to yours and I'd be interested in your feedback and possibly even collaboration. 
Here is the operator[1], it's still being developed, I hope to cut the first release soon. Anyway I think you will immediately see where it is going and the difference in approach.

[1]: https://github.com/redhat-cop/vault-config-operator

**Comment by patoarvizu** [comment]
Hey sorry it took me a while to reply. I haven't been able to directly play with it, but it looks great! It is certainly a different approach, specially because `vault-dynamic-configuration-operator` is designed to **only** work with [bank-vaults](https://github.com/banzaicloud/bank-vaults), while yours (from what I understand) is compatible with just any Vault control plane, regardless of how it's provisioned. It's also great that you are providing multi-arch images.

Is there explicit support for Kubernetes, or is there anything that makes it OpenShift-only? I know you can deploy to Kubernetes through OLM, but I don't know if this project's manifests/workloads themselves have something specific to OpenShift.

Also, great job on the documentation! Everything can always be improved, but it's a great start.

I don't have an immediate need for something like this, but I'll take a look and see if I can contribute or at least have any feedback, and I'll ping you on the other project. In the meantime, I'll star your repo and it'd be awesome if you starred mine 🙂

Closing this issue now.

**Comment by raffaelespazzoli** [comment]
We will release the operator as both a OLM bundle and a helm chart. It should work the same on both Kubernetes and OpenShift (although I really test OCP only).
